NHibernate/Models/Store.cs
using System.Collections.Generic;

namespace NHibernateTest.Models
{
    public class Store
    {
        public Store()
        {
            Products = new List<Product>();
            Staff = new List<Employee>();
        }

        public virtual int Id { get; set; }
        public virtual string Name { get; set; }
        public virtual IList<Product> Products { get; set; }
        public virtual IList<Employee> Staff { get; set; }

        public virtual void AddEmployee(Employee employee)
        {
            employee.Store = this;
            Staff.Add(employee);
        }

        public virtual void AddProduct(Product product)
        {
            product.StoresStockedIn.Add(this);
            Products.Add(product);
        }
    }
}

NHibernate/Controllers/EmployeeController.cs
using AutoMapper;
using NHibernateTest.Domain.Entities;
using NHibernateTest.Domain.Services;
using NHibernateTest.Models;
using System.Web.Mvc;

namespace NHibernateTest.Controllers
{
    public class EmployeeController : BaseController
    {
        private readonly IEmployeeService _employeeService;

        public EmployeeController(IEmployeeService employeeService)
        {
            _employeeService = employeeService;
        }

        // GET: Employee/Create
        public ActionResult Create(int parentId)
        {
            var model = new EmployeeViewModel { StoreId = parentId };
            return View(model);
        }

        // POST: Employee/Create
        [HttpPost]
        public ActionResult Create(EmployeeViewModel model)
        {
            if (ModelState.IsValid)
            {
                var employee = Mapper.Map(model, new Employee());
                _employeeService.CreateForStore(employee, model.StoreId);
                return RedirectToAction("Index", "Store", new { id = model.Id });
            }
            else
            {
                return View();
            }
        }

        // GET: Employee/Delete/5
        public ActionResult Delete(int id)
        {
            var model = _employeeService.GetById(id);
            var viewModel = Mapper.Map<EmployeeViewModel>(model);
            return View(viewModel);
        }

        // POST: Employee/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, EmployeeViewModel model)
        {
            try
            {
                _employeeService.Delete(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Employee/Details/5
        public ActionResult Details(int id)
        {
            var model = _employeeService.GetById(id);
            var viewModel = Mapper.Map<EmployeeViewModel>(model);
            return View(viewModel);
        }

        // GET: Employee/Edit/5
        public ActionResult Edit(int id)
        {
            var model = _employeeService.GetById(id);
            var viewModel = Mapper.Map<EmployeeViewModel>(model);
            return View(viewModel);
        }

        // POST: Employee/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, EmployeeViewModel model)
        {
            if (ModelState.IsValid)
            {
                var employee = _employeeService.GetById(id);
                Mapper.Map(model, employee);
                _employeeService.Update(employee);
                return RedirectToAction("Details", "Store", new { id = model.Id });
            }
            else
            {
                return View();
            }
        }
    }
}

NHibernate/Controllers/ProductController.cs
using AutoMapper;
using NHibernateTest.Domain.Entities;
using NHibernateTest.Domain.Services;
using NHibernateTest.Models;
using System.Collections.Generic;
using System.Web.Mvc;

namespace NHibernateTest.Controllers
{
    public class ProductController : BaseController
    {
        private readonly IProductService _productService;

        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        // GET: Product/Create
        public ActionResult Create(int parentId = 0)
        {
            var model = new ProductViewModel { StoreId = parentId };
            return View(model);
        }

        // POST: Product/Create
        [HttpPost]
        public ActionResult Create(ProductViewModel model)
        {
            if (ModelState.IsValid)
            {
                var product = Mapper.Map(model, new Product());

                if (model.StoreId != 0)
                {
                    _productService.CreateForStore(product, model.StoreId);
                    return RedirectToAction("Details", "Store", new { id = model.StoreId });
                }
                else
                {
                    _productService.Create(product);
                    return RedirectToAction("Index");
                }
            }
            else
            {
                return View();
            }
        }

        // GET: Product/Delete/5
        public ActionResult Delete(int id)
        {
            var product = _productService.GetById(id);
            var viewModel = Mapper.Map<ProductViewModel>(product);
            return View(viewModel);
        }

        // POST: Product/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, ProductViewModel model)
        {
            try
            {
                _productService.Delete(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Product/Details/5
        public ActionResult Details(int id)
        {
            var product = _productService.GetById(id);
            var viewModel = Mapper.Map<ProductViewModel>(product);
            return View(viewModel);
        }

        // GET: Product/Edit/5
        public ActionResult Edit(int id)
        {
            var product = _productService.GetById(id);
            var viewModel = Mapper.Map<ProductViewModel>(product);
            return View(viewModel);
        }

        // POST: Product/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, ProductViewModel model)
        {
            if (ModelState.IsValid)
            {
                var product = _productService.GetById(id);
                Mapper.Map(model, product);
                _productService.Update(product);

                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        public ActionResult Index()
        {
            var products = _productService.GetAll();
            var viewmodels = Mapper.Map<IList<ProductViewModel>>(products);
            return View(viewmodels);
        }
    }
}

NHibernate/Controllers/StoreController.cs
using NHibernateTest.Domain.Entities;
using NHibernateTest.Domain.Services;
using System;
using System.Web.Mvc;

namespace NHibernateTest.Controllers
{
    public class StoreController : BaseController
    {
        private readonly IStoreService _storeService;

        public StoreController(IStoreService storeService)
        {
            _storeService = storeService;
        }

        // GET: Store/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Store/Create
        [HttpPost]
        public ActionResult Create(Store model)
        {
            if (ModelState.IsValid)
            {
                _storeService.Create(model);
                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
        }

        // GET: Store/Delete/5
        public ActionResult Delete(int id)
        {
            var result = _storeService.GetById(id);
            return View(result);
        }

        // POST: Store/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Store model)
        {
            try
            {
                _storeService.Delete(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Store/Details/5
        public ActionResult Details(int id)
        {
            var result = _storeService.GetEagerById(id);
            return View(result);
        }

        // GET: Store/Edit/5
        public ActionResult Edit(int id)
        {
            var result = _storeService.GetById(id);
            return View(result);
        }

        // POST: Store/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Store model)
        {
            try
            {
                var store = _storeService.GetById(id);
                store.Name = model.Name;
                _storeService.Update(store);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return View();
            }
        }

        // GET: Store
        public ActionResult Index()
        {
            var stores = _storeService.GetAll();
            return View(stores);
        }
    }
}

NHibernate/Views/Store/Create.cshtml
@model NHibernateTest.Domain.Entities.Store

@{
    ViewBag.Title = "View";
}

<h2>View</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Store</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NHibernate/Views/Store/Delete.cshtml
@model NHibernateTest.Domain.Entities.Store

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Store</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

NHibernate/Views/Store/Details.cshtml
@model NHibernateTest.Domain.Entities.Store

@{
    ViewBag.Title = "View";
}

<h2>View</h2>

<div>
    <h4>Store</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    <h4>Products</h4>
    <p>
        @Html.ActionLink("Dodaj product", "Create", "Product", new { parentId = Model.Id }, null)
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.Products)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", "Product", new { id = item.Id, parentId = Model.Id }, null) |
                    @Html.ActionLink("Details", "Details", "Product", new { id = item.Id, parentId = Model.Id }, null) |
                    @Html.ActionLink("Delete", "Delete", "Product", new { id = item.Id, parentId = Model.Id }, null)
                </td>
            </tr>
        }
        </table>
    <h4>Staff</h4>
    <p>
        @Html.ActionLink("Dodaj pracownika", "Create", "Employee", new { parentId = Model.Id }, null)
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
        @foreach (var item in Model.Staff)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", "Employee" ,new { id = item.Id, parentId = Model.Id }, null) |
                    @Html.ActionLink("Details", "Details", "Employee", new { id = item.Id, parentId = Model.Id }, null) |
                    @Html.ActionLink("Delete", "Delete", "Employee", new { id = item.Id, parentId = Model.Id }, null)
                </td>
            </tr>
        }
        </table>
</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

NHibernate/Views/Store/Edit.cshtml
@model NHibernateTest.Domain.Entities.Store

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Store</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

NHibernate/Views/Store/Index.cshtml
@model IEnumerable<NHibernateTest.Domain.Entities.Store>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}
</table>